package com.tiantian.good.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "goods")
public class Goods extends BaseDTO {

    public static final String FIELD_GID = "gid";
    public static final String FIELD_PNAME = "pname";
    public static final String FIELD_OLDPRICE = "oldprice";
    public static final String FIELD_PRICE = "price";
    public static final String FIELD_LOCAL = "local";
    public static final String FIELD_JIANJIE = "jianjie";
    public static final String FIELD_IMG = "img";
    public static final String FIELD_TID = "tid";
    public static final String FIELD_IMG2 = "img2";
    public static final String FIELD_IMG3 = "img3";
    public static final String FIELD_IMG4 = "img4";
    public static final String FIELD_IMG5 = "img5";
    public static final String FIELD_KUCUN = "kucun";


    @Id
    @GeneratedValue
    private Long gid;

    @Length(max = 50)
    private String pname;

    private Long oldprice;

    private Long price;

    @Length(max = 10)
    private String local;

    @Length(max = 65535)
    private String jianjie;

    @Length(max = 65535)
    private String img;

    private String tid;

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    @Length(max = 65535)
    private String img2;

    @Length(max = 65535)
    private String img3;

    @Length(max = 65535)
    private String img4;

    @Length(max = 65535)
    private String img5;

    private Long kucun;

    @Transient
    private Long min_price;

    @Transient
    private Long max_price;

    public Long getMin_price() {
        return min_price;
    }

    public void setMin_price(Long min_price) {
        this.min_price = min_price;
    }

    public Long getMax_price() {
        return max_price;
    }

    public void setMax_price(Long max_price) {
        this.max_price = max_price;
    }

    public void setGid(Long gid) {
        this.gid = gid;
    }

    public Long getGid() {
        return gid;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    public String getPname() {
        return pname;
    }

    public void setOldprice(Long oldprice) {
        this.oldprice = oldprice;
    }

    public Long getOldprice() {
        return oldprice;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public Long getPrice() {
        return price;
    }

    public void setLocal(String local) {
        this.local = local;
    }

    public String getLocal() {
        return local;
    }

    public void setJianjie(String jianjie) {
        this.jianjie = jianjie;
    }

    public String getJianjie() {
        return jianjie;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getImg() {
        return img;
    }

    public void setImg2(String img2) {
        this.img2 = img2;
    }

    public String getImg2() {
        return img2;
    }

    public void setImg3(String img3) {
        this.img3 = img3;
    }

    public String getImg3() {
        return img3;
    }

    public void setImg4(String img4) {
        this.img4 = img4;
    }

    public String getImg4() {
        return img4;
    }

    public void setImg5(String img5) {
        this.img5 = img5;
    }

    public String getImg5() {
        return img5;
    }

    public void setKucun(Long kucun) {
        this.kucun = kucun;
    }

    public Long getKucun() {
        return kucun;
    }

}
