package com.tiantian.tt.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "goodorder")
public class Goodorder extends BaseDTO {

     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_GID = "gid";
     public static final String FIELD_COUNT = "count";
     public static final String FIELD_USERNAME = "username";
     public static final String FIELD_PNAME = "pname";
     public static final String FIELD_PERSON = "person";
     public static final String FIELD_LOCAL = "local";
     public static final String FIELD_DATE = "date";
     public static final String FIELD_TEL = "tel";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_TOTAL_PRICE = "totalPrice";
     public static final String FIELD_GOODCODE = "goodcode";


     @Id
     @GeneratedValue
     private Long orderId;

     private Long gid;

     private Long count;

     @Length(max = 20)
     private String username;

     @Length(max = 20)
     private String pname;

     @Length(max = 20)
     private String person;

     @Length(max = 65535)
     private String local;

    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date date;

     @Length(max = 20)
     private String tel;

     @Length(max = 255)
     private String status;

     private Long totalPrice;

     @Length(max = 255)
     private String goodcode;


     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setGid(Long gid){
         this.gid = gid;
     }

     public Long getGid(){
         return gid;
     }

     public void setCount(Long count){
         this.count = count;
     }

     public Long getCount(){
         return count;
     }

     public void setUsername(String username){
         this.username = username;
     }

     public String getUsername(){
         return username;
     }

     public void setPname(String pname){
         this.pname = pname;
     }

     public String getPname(){
         return pname;
     }

     public void setPerson(String person){
         this.person = person;
     }

     public String getPerson(){
         return person;
     }

     public void setLocal(String local){
         this.local = local;
     }

     public String getLocal(){
         return local;
     }

     public void setDate(Date date){
         this.date = date;
     }

     public Date getDate(){
         return date;
     }

     public void setTel(String tel){
         this.tel = tel;
     }

     public String getTel(){
         return tel;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setTotalPrice(Long totalPrice){
         this.totalPrice = totalPrice;
     }

     public Long getTotalPrice(){
         return totalPrice;
     }

     public void setGoodcode(String goodcode){
         this.goodcode = goodcode;
     }

     public String getGoodcode(){
         return goodcode;
     }

     }
